### ISSUE TITLE
Error in the gulpfile

### ISSUE THREAD

**Issue by bryantorresvega** [obetomuniz/ionic-google-maps-starter#12]
WARN: ionic.project has been renamed to ionic.config.json, please rename it.

There is an error in your gulpfile: 
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/Users/Computos/Desktop/ionic-google-maps-starter-master/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/Users/Computos/Desktop/ionic-google-maps-starter-master/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/Computos/Desktop/ionic-google-maps-starter-master/node_modules/gulp-sass/index.js:3:17)
    at Module._compile (module.js:409:26)

**Comment by hparth** [comment]
up vote
294
down vote
If your node version is 4 and you are using gulp-sass, then try

npm uninstall --save-dev gulp-sass

npm install --save-dev gulp-sass@2

Reference : http://stackoverflow.com/questions/28409100/try-reinstalling-node-sass-on-node-0-12

**Comment by obetomuniz** [comment]
Thanks for the answer @hparth. Seems that @bryantorresvega fix the problem, once he doesn't return here to give a feedback.
